"""initial

Revision ID: 74b6fcb0619d
Revises: de47c396dc6f
Create Date: 2023-07-08 22:36:48.614209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '74b6fcb0619d'
down_revision = 'de47c396dc6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.String(), nullable=False),
    sa.Column('message_sum', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_index('ix_histories_id', table_name='histories')
    op.drop_table('histories')
    op.add_column('users', sa.Column('sum', sa.Float(), default=0, nullable=True))
    op.alter_column('users', 'tokens_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tokens_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'sum')
    op.create_table('histories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('sum', sa.FLOAT(), nullable=False),
    sa.Column('messages', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_histories_id', 'histories', ['id'], unique=False)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###