"""adding tokens_value column

Revision ID: 9ec7ca62909f
Revises: b266c29a9c9b
Create Date: 2023-07-05 21:18:47.114550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec7ca62909f'
down_revision = 'b266c29a9c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tokens_value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tokens_value')
    # ### end Alembic commands ###